// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(LeadDbContext))]
    [Migration("20251025030448_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Suburb")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("Leads");

                    b.HasData(
                        new
                        {
                            Id = new Guid("467f6177-98e7-4412-ae14-d5406aa1295b"),
                            Category = "Plumbing",
                            ContactEmail = "john.doe@example.com",
                            ContactFirstName = "John",
                            ContactLastName = "Doe",
                            CreatedAt = new DateTime(2025, 10, 25, 3, 4, 48, 146, DateTimeKind.Utc).AddTicks(8259),
                            Description = "Fix leaking faucet",
                            Price = 150.00m,
                            Status = 0,
                            Suburb = "Sydney"
                        },
                        new
                        {
                            Id = new Guid("a27b1e4a-1b1f-4fe6-9f1b-67d5948cb4d8"),
                            Category = "Electrical",
                            ContactEmail = "jane.smith@example.com",
                            ContactFirstName = "Jane",
                            ContactLastName = "Smith",
                            ContactPhone = "123-456-7890",
                            CreatedAt = new DateTime(2025, 10, 25, 3, 4, 48, 146, DateTimeKind.Utc).AddTicks(8259),
                            Description = "Install new light fixtures",
                            Price = 300.00m,
                            Status = 1,
                            Suburb = "Melbourne"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
